clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  check-app-compatbility:
    image: nextcloudci/php7.0:php7.0-17
    environment:
      - APP_NAME=social
      - CORE_BRANCH=stable15
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
      # Code checker
      - ./occ app:check-code $APP_NAME -c strong-comparison
      - ./occ app:check-code $APP_NAME -c deprecation
    when:
      matrix:
        TESTS: check-app-compatbility
  syntax-php7.0:
    image: nextcloudci/php7.0:php7.0-17
    environment:
      - APP_NAME=social
      - CORE_BRANCH=stable15
      - DB=sqlite
    commands:
      - composer install
      - ./vendor/bin/parallel-lint --exclude ./vendor/ .
    when:
      matrix:
        TESTS: syntax-php7.0
  syntax-php7.1:
    image: nextcloudci/php7.1:php7.1-15
    environment:
      - APP_NAME=social
      - CORE_BRANCH=stable15
      - DB=sqlite
    commands:
      - composer install
      - ./vendor/bin/parallel-lint --exclude ./vendor/ .
    when:
      matrix:
        TESTS: syntax-php7.1
  syntax-php7.2:
    image: nextcloudci/php7.2:php7.2-9
    environment:
      - APP_NAME=social
      - CORE_BRANCH=stable15
      - DB=sqlite
    commands:
      - composer install
      - ./vendor/bin/parallel-lint --exclude ./vendor/ .
    when:
      matrix:
        TESTS: syntax-php7.2
  syntax-php7.3:
    image: nextcloudci/php7.3:php7.3-2
    environment:
      - APP_NAME=social
      - CORE_BRANCH=stable15
      - DB=sqlite
    commands:
      - composer install
      - ./vendor/bin/parallel-lint --exclude ./vendor/ .
    when:
      matrix:
        TESTS: syntax-php7.3
  eslint:
    image: nextcloudci/jsunit:jsunit-5
    commands:
      - npm install
      - npm run lint
    when:
      matrix:
        TESTS: eslint
  vue-build:
    image: nextcloudci/jsunit:jsunit-5
    group: build
    commands:
      - npm install
      - npm run build
    when:
      matrix:
        TESTS: vue-build

  frontend-build-javascript:
    image: nextcloudci/jsunit:jsunit-5
    group: build
    commands:
    - npm install
    - npm rebuild node-sass
    - npm run build
    when:
      matrix:
        TESTS: frontenda
  frontend-build-php:
    image: nextcloudci/acceptance-php7.1:acceptance-php7.1-2
    group: build
    commands:
    - composer install
    when:
      matrix:
        TESTS: frontend
  frontend-server:
    image: nextcloudci/acceptance-php7.1:acceptance-php7.1-2
    group: test
    detach: true
    environment:
    - APP_NAME=social
    - CORE_BRANCH=master
    - DB=sqlite
    commands:
    # Checkout the latest server
    - git clone --depth 1 -b master https://github.com/nextcloud/server /drone/server
    - cd /drone/server
    - ln --symbolic $(pwd) /var/www/html
    - git submodule update --init

    # Add app sources to the app director
    - cp -R /drone/src /drone/server/apps/social

    # Install server
    - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/core_install.sh && bash core_install.sh sqlite
    - php occ app:enable social
    - php occ config:system:set trusted_domains 2 --value=frontend-server
    - export OC_PASS=p4ssw0rd
    - php occ user:add --password-from-env --display-name="Jane Doe" janedoe
    - php occ user:add --password-from-env --display-name="John Doe" johndoe
    - touch /drone/server/data/nextcloud.log
    - chown -R www-data:www-data /drone/server

    # Watch logs and run apache
    - tail -f /drone/server/data/nextcloud.log &
    - . /etc/apache2/envvars
    - apache2 -DFOREGROUND
    when:
      matrix:
        TESTS: frontend
  frontend-test:
    image: cypress/browsers:chrome69
    group: test
    environment:
    - APP_NAME=social
    - CORE_BRANCH=master
    - DB=sqlite
    commands:
    - npm install
    - npm rebuild node-sass
    - npm run build
    - bash -c "until curl -s http://frontend-server > /dev/null; do sleep 2; done"
    - curl -v http://frontend-server/index.php/
    - $(npm bin)/cypress install
    - CYPRESS_baseUrl=http://frontend-server/index.php/ $(npm bin)/cypress run # --record --key $CYPRESS_RECORD_TOKEN
    secrets: [ cypress_record_token ]
    when:
      matrix:
        TESTS: frontend

matrix:
  include:
    - TESTS: check-app-compatbility
    - TESTS: syntax-php7.0
    - TESTS: syntax-php7.1
    - TESTS: syntax-php7.2
    - TESTS: syntax-php7.3
    - TESTS: eslint
    - TESTS: frontend
    - TESTS: vue-build


branches: [ master, stable*, alpha1 ]
